### ISSUE TITLE
A more permissive license for iOS users?

### ISSUE THREAD

**Issue by dodikk** [Ithildir/liferay-sdk-builder-windows#5]
According to [Xamarin.iOS docs](https://developer.xamarin.com/guides/ios/advanced_topics/linker/), the resulting binary file is linked statically into an assembly file (since `Ahead Of Time Compilation` is used).

As far as I know, the LGPL license forces to disclose the commercial code of the app in this case. Which is most likely not acceptable for mobile app developers.

**Comment by Ithildir** [comment]
I'm open to change the license, no problem 😊 Do you have any suggestion?

**Comment by dodikk** [comment]
These are most widely used for iOS opensource projects
* BSD (3 clause)
* MIT

---

This one is going to be fine as well
* Apache License 2.0

**Comment by dodikk** [comment]
Here is a simple guide that makes sense to me https://choosealicense.com

**Comment by dodikk** [comment]
Here are some manuals from github that might help

* https://help.github.com/articles/licensing-a-repository/
* http://www.addalicense.com
